<?php /*ř*/	
if ($article_img_2 != ""){ echo"<img src=\"edencms_files/img_articles/".$article_img_2."\" alt=\"\" width=\"150\" height=\"150\" border=\"1\" align=\"left\" class=\"img_articles\">"; }else{ echo "<img src=\"edencms_files/img_articles/".$article_img_1."\" alt=\"\" width=\"100\" height=\"100\" border=\"1\" align=\"left\" class=\"img_articles\">"; }
echo "<h"; if ($num == 0){echo "1";} else { echo "2";} echo " class=\"best_article\"><img src=\"".$url_category.$category_image."\" title=\"".$category_name."\" alt=\"".$category_name."\" width=\"16\" height=\"16\" border=\"0\">&nbsp;"; if ($article_link == "TRUE"){ echo "<a href=\"index.php?lang=".AGet($_GET,'lang')."&amp;filter=".AGet($_GET,'filter')."&amp;action=clanek&amp;id=".$article_id."&amp;page_mode=".AGet($_GET,'page_mode')."\" title=\"".$article_headline."\">".$article_headline."</a>"; } else {echo $article_headline;} echo "</h"; if ($num == 0){echo "1";} else { echo "2";} echo ">\n";
echo "	<strong>".FormatTimestamp($article_date_on,"d/m/Y")." - <a href=\"index.php?lang=".AGet($_GET,'lang')."&amp;action=user_details&amp;user_id=".$admin_id."&amp;filter=".AGet($_GET,'filter')."&amp;page_mode=".AGet($_GET,'page_mode')."\">".$admin_nickname."</a></strong> ("; if ($_SESSION['u_status'] == "admin"){ echo _COM_COM_VIEWS." "; if($article_views > 70){echo $article_views * 3;} else {echo $article_views;} echo "&nbsp;";} if ($article_comments != "0"){ echo " <a href=\"index.php?lang=".AGet($_GET,'lang')."&amp;filter=".AGet($_GET,'filter')."&amp;action=komentar&amp;id=".$article_id."&amp;modul=article&amp;page_mode=".AGet($_GET,'page_mode')."&amp;page_mode=".AGet($_GET,'page_mode')."\" target=\"_self\">"._COM_COM." ".$num2[0]."</a>"; } if (($_SESSION['u_status'] == "user" || $_SESSION['u_status'] == "admin") && ($comments_log_comments < $num2[0])){$new_comments = ($num2[0] - $comments_log_comments); echo "&nbsp; <a href=\"index.php?lang=".AGet($_GET,'lang')."&amp;filter=".AGet($_GET,'filter')."&amp;action=komentar&amp;id=".$article_id."&amp;modul=article&amp;page_mode=".AGet($_GET,'page_mode')."\" target=\"_self\">"._COM_COM_NEW." ".$new_comments."</a>"; } echo ")<br>\n";
		if ($article_link == "TRUE"){echo $article_perex;} else {echo $article_text;} echo "<br>\n";
echo "	<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n";
echo "		<tr>\n";
echo "	   		<td width=\"496\" align=\"left\">&nbsp;&nbsp;"; if ($article_source != ""){echo _ARTICLES_SOURCE.": ".ShowSource($article_source); } echo "</td>\n";
echo "			<td width=\"100\" align=\"right\">";  if ($article_ftext == 1){ echo "<a href=\"index.php?action=clanek&amp;id=".$article_id."&amp;lang=".AGet($_GET,'lang')."&amp;filter=".AGet($_GET,'filter')."&amp;page_mode=".AGet($_GET,'page_mode')."\" target=\"_self\">"._FULL_ARTICLE."</a>"; } echo "</td>\n";
echo "		</tr>\n";
echo "	</table>";